### ISSUE TITLE
KMSEncryptDecryptTest and End2EndTest dependant on AWS

### ISSUE THREAD

**Issue by quest313** [julianghionoiu/kms-jwt#1]
Currently both tests require access to specific resources and corresponding credentials. Preferably Unit tests could take advantage of mocking.

**Comment by julianghionoiu** [comment]
Hey Ben,

I agree it would be nice to remove the dependency on the real AWS.
The best way I could think of is to create a simple local service that implements the KMS encrypt/decrypt API.

It would be possible to mock the client, but I think the integration with KMS is an integral part of this library and mocking the client would possibly mask some config issues.

For now, the best way to run the test again your account is to pass the TEST_AWS_REGION and TEST_AWS_KEY_ARN as environment variables.

Cheers,
 Julian

**Comment by quest313** [comment]
I agree it is useful for an integration style test. I posted this before I saw the environment variable bit. Thanks for following up.
